sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.3



env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "N9f5lAKBqZCXRVKc5Qxq80VO3RwEqh318QJCiD82YT5ctL87Q1ekDuMDaCfIRmopFq3psyEEeEwLkMY0BwZIsScHaLv4wIVerMEhj28kv5WaEAnVQYEux0dAmn+Hom+Oom9aoDDYXWFdjzWEeCaJuMWkQfQ1baS4BmWuu/dEWZE+NKtwkgM8FzM7WFOdgKCYVp6R+6wyfAlaFaumzeXON5/1Wam/OaU1eTXWG/E0FezhRAZNVt3LeVRijTPq2ETMYhTXeg32uT6APdxRCTJ+CzutlG5ho63gAjtfCrc6oH0/6CkhV+0TWAhdaGzb2d041vh4Wg/KxYzj/5LDn2KKLVcmySBtLOj7xENGkvCI49YqUFHeNciWcfHKQMogTt1FTeTb35vTNqVzwbU+mqlv00YYG3tfZN6uCYN2uUE6r1wBz3J8mbbhcgVjLpECMz9nla4VBsfNbTl3BJtmoNqAeNsAlhTdSuchrhTQnOsibtnAk2bfi73bqGG9uDmrJbPhFKCXUTmMfb2xpO4VCnkBpG2xsTB16ws2AL/1+IYKI7a19CjVRun8z40xlX6WmwfN7IoYMYaCVzCU8xIlRno7ezu/IxOUvecBiVXc+OLYMvDXF+AdsKfCQU0Zw0ALC4cwZqi0ncAaAp6hlY0743g3RkHpJkwg0oL3tP3KBGKS+QQ="
    - secure: "QgplMQeIkiGiAH1B+xbogwFFz8jTaD2Gsi0xe1zPPTFdpJZ3ljgw7moB898wcZHPw9lM3eOBF0dwpiOP44luafjoAe9b2ieXfyICBTFFQY0L5GKhqha72ZRDuBNox9VzC5XCgzZMZzXiw7BieaP1CFccCBGQUSKExfhWbra1JHAXalwWvLNOgT7SHUoGrruKacBbhAMEoadMRqMkKTmNSvNMetuLRxwjKPH7dd2bIqpwNngQb1NHfMC42CzX/rzavoVFcydUH3KL7dxwSRQzVW+QlM6IpKEKggCuDWjaEn6f0EvkB8PVvPQr1YJ7Sm3lfZzZuSu73rykcLPdSoAPJ+ocNzoaY5HoG6N2zavLPZ0TVcsITif5YsdcXNNffMypuS+ZFfzwvfcjsx94n7YOjAGeYN4NpXG5sFKHA2ieICr5rh5Ju4D5+D9Qu7W1gtaqYVO7VYxKJxqoooDIUsnofpEXF1HLgt6Sfbfbe/HjBt7hGiJW6c/PQqPoFh6A//v6540/6uYI3bH/aU4EoHJLEG/SKPdAch3Te8pxzpNb+2wqZN5YEt40xBf0cUodGRTAGX4qku/uou+yGYALP4r0l98lhJiUmput9tIJQL/5hTVYP0fsfKeLC4CakXi4EmI8cxdywc1pdn06ZBhBpLYushZIb/Dgzt600vjlj7FutRQ="

    

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=pmaciejo/testrepo
  - docker build . -f Dockerfile -t $REPO:$COMMIT
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO 

